# Generated by Django 4.0.6 on 2022-07-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cool', '0002_the_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='the_member',
            name='year_of_study',
            field=models.IntegerField(),
        ),
    ]
