# Generated by Django 4.0.6 on 2022-07-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cool', '0003_alter_the_member_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='the_member',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'MALE')], max_length=6),
        ),
    ]
