# Generated by Django 4.0.6 on 2022-09-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cool', '0005_alter_the_member_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('sir_name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=6)),
                ('leader_status', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
