# Generated by Django 4.0.6 on 2022-09-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cool', '0007_biblestudymember_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblestudymember',
            name='activated',
        ),
    ]
