# Generated by Django 4.0.6 on 2022-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cool', '0010_rename_groups_groups_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='the_member',
            name='leader_pre_status',
        ),
        migrations.AlterField(
            model_name='groups_backup',
            name='info',
            field=models.CharField(max_length=1000),
        ),
    ]
