# Generated by Django 4.0.6 on 2022-10-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cool', '0011_remove_the_member_leader_pre_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblestudymember',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1),
        ),
    ]
