# Generated by Django 4.1.2 on 2022-10-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cool', '0012_alter_biblestudymember_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblestudymember',
            name='id',
        ),
        migrations.AlterField(
            model_name='biblestudymember',
            name='phone_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='biblestudymember',
            name='sir_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
