# Generated by Django 4.1.2 on 2022-10-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cool', '0014_alter_biblestudymember_sir_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BStudyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('sir_name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('leader_status', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
